// Mock data, used until the Tauri/Rust backend is wired in.
// All dates are computed relative to "now" so the demo always looks fresh.

import type { Account, Folder, Mail, Thread, Label } from '@/types';

const now = Date.now();
const minutes = (n: number) => new Date(now - n * 60_000).toISOString();
const hours = (n: number) => new Date(now - n * 3_600_000).toISOString();
const days = (n: number) => new Date(now - n * 86_400_000).toISOString();

export const mockAccounts: Account[] = [
  {
    id: 'acc_perso',
    email: 'jordan@perso.fr',
    displayName: 'Jordan',
    protocol: 'imap',
    color: '#6366f1',
    signature: '— Jordan',
  },
  {
    id: 'acc_pro',
    email: 'j.lafe@triskell.studio',
    displayName: 'Jordan Lafe',
    protocol: 'jmap',
    color: '#0ea5e9',
    signature: 'Jordan Lafe — Triskell Studio\nhttps://triskell.studio',
  },
];

export const mockFolders: Folder[] = [
  { id: 'inbox_perso', accountId: 'acc_perso', name: 'Boîte de réception', type: 'inbox', unreadCount: 4 },
  { id: 'sent_perso', accountId: 'acc_perso', name: 'Envoyés', type: 'sent', unreadCount: 0 },
  { id: 'drafts_perso', accountId: 'acc_perso', name: 'Brouillons', type: 'drafts', unreadCount: 0 },
  { id: 'archive_perso', accountId: 'acc_perso', name: 'Archives', type: 'archive', unreadCount: 0 },
  { id: 'inbox_pro', accountId: 'acc_pro', name: 'Inbox', type: 'inbox', unreadCount: 8 },
  { id: 'sent_pro', accountId: 'acc_pro', name: 'Sent', type: 'sent', unreadCount: 0 },
  { id: 'drafts_pro', accountId: 'acc_pro', name: 'Drafts', type: 'drafts', unreadCount: 2 },
];

export const mockLabels: Label[] = [
  { id: 'lbl_clients', name: 'Clients', color: '#22c55e' },
  { id: 'lbl_facturer', name: 'À facturer', color: '#f59e0b' },
  { id: 'lbl_attente', name: 'En attente', color: '#a855f7' },
];

export const mockMails: Mail[] = [
  {
    id: 'm1',
    threadId: 't1',
    accountId: 'acc_pro',
    folder: 'inbox_pro',
    labels: ['lbl_clients'],
    from: { name: 'Anna Belmas', email: 'anna.belmas@triskell.fr' },
    to: [{ email: 'j.lafe@triskell.studio' }],
    cc: [],
    bcc: [],
    subject: 'Confirmation réunion jeudi 14h',
    bodyText:
      "Bonjour Jordan,\n\nJe confirme notre RDV jeudi 14h en salle 3. Je t'envoie le brief lundi matin pour qu'on soit aligné.\n\nMerci,\nAnna",
    receivedAt: minutes(13),
    read: false,
    starred: false,
    category: 'work',
    priority: 'normal',
    trackersBlocked: 0,
    references: [],
    attachments: [],
    engagements: [{ text: "Je t'envoie le brief lundi matin", reminded: false }],
  },
  {
    id: 'm2',
    threadId: 't2',
    accountId: 'acc_pro',
    folder: 'inbox_pro',
    labels: [],
    from: { name: 'Notion', email: 'notifications@notion.so' },
    to: [{ email: 'j.lafe@triskell.studio' }],
    cc: [],
    bcc: [],
    subject: 'Newsletter Build #142 — what shipped this week',
    bodyText:
      "Hello, this week we shipped 12 features including a new database view, faster search, and revamped sharing options. Read more on the blog.",
    receivedAt: minutes(85),
    read: true,
    starred: false,
    category: 'newsletters',
    priority: 'normal',
    trackersBlocked: 4,
    references: [],
    attachments: [],
  },
  {
    id: 'm3',
    threadId: 't3',
    accountId: 'acc_pro',
    folder: 'inbox_pro',
    labels: [],
    from: { name: 'GitHub', email: 'noreply@github.com' },
    to: [{ email: 'j.lafe@triskell.studio' }],
    cc: [],
    bcc: [],
    subject: '[teddy-mail] PR #283 needs review',
    bodyText:
      "A pull request requires your review:\n\nRefactor: extract IMAP sync into Tauri command\n\nView on GitHub: https://github.com/teddy-mail/pull/283",
    receivedAt: hours(4),
    read: false,
    starred: true,
    category: 'notifications',
    priority: 'high',
    trackersBlocked: 1,
    references: [],
    attachments: [],
  },
  {
    id: 'm4',
    threadId: 't4',
    accountId: 'acc_perso',
    folder: 'inbox_perso',
    labels: ['lbl_facturer'],
    from: { name: 'Stripe', email: 'no-reply@stripe.com' },
    to: [{ email: 'jordan@perso.fr' }],
    cc: [],
    bcc: [],
    subject: 'Paiement reçu — 1 240,00 EUR',
    bodyText:
      "Vous avez reçu un paiement de 1 240,00 EUR de Client SAS. Le virement sera disponible sous 2 jours ouvrés.",
    receivedAt: hours(22),
    read: false,
    starred: false,
    category: 'notifications',
    priority: 'normal',
    trackersBlocked: 2,
    references: [],
    attachments: [],
  },
  {
    id: 'm5',
    threadId: 't5',
    accountId: 'acc_perso',
    folder: 'inbox_perso',
    labels: [],
    from: { name: 'Marie Dupont', email: 'marie@famille.fr' },
    to: [{ email: 'jordan@perso.fr' }],
    cc: [],
    bcc: [],
    subject: 'Photos vacances Bretagne',
    bodyText:
      "Salut frérot, je te mets les photos en pièce jointe. On rentre dimanche soir, à très vite.\nM.",
    receivedAt: days(1),
    read: true,
    starred: false,
    category: 'personal',
    priority: 'normal',
    trackersBlocked: 0,
    references: [],
    attachments: [
      { id: 'a1', filename: 'plage_dinan.jpg', mimeType: 'image/jpeg', sizeBytes: 2_419_018, contentHash: 'sha:aaa1' },
      { id: 'a2', filename: 'phare_minou.jpg', mimeType: 'image/jpeg', sizeBytes: 1_812_220, contentHash: 'sha:bbb2' },
    ],
  },
  {
    id: 'm6',
    threadId: 't6',
    accountId: 'acc_perso',
    folder: 'inbox_perso',
    labels: [],
    from: { name: 'Booking.com', email: 'noreply@booking.com' },
    to: [{ email: 'jordan@perso.fr' }],
    cc: [],
    bcc: [],
    subject: 'Promotion: 30% off your next stay',
    bodyText:
      "Save 30% on hotels in Paris, Lyon, and Marseille. Book before Sunday to lock in the discount.",
    receivedAt: days(2),
    read: false,
    starred: false,
    category: 'promotions',
    priority: 'normal',
    trackersBlocked: 8,
    references: [],
    attachments: [],
  },
  {
    id: 'm7',
    threadId: 't7',
    accountId: 'acc_pro',
    folder: 'inbox_pro',
    labels: ['lbl_attente'],
    from: { name: 'Lucas Petit', email: 'lucas@studio-lune.com' },
    to: [{ email: 'j.lafe@triskell.studio' }],
    cc: [],
    bcc: [],
    subject: 'Re: Devis projet Lune',
    bodyText:
      "Hello Jordan,\n\nMerci pour le devis. On revient vers toi vendredi avec une décision.\n\nLucas",
    receivedAt: days(2),
    read: true,
    starred: false,
    category: 'work',
    priority: 'normal',
    trackersBlocked: 0,
    references: [],
    attachments: [
      { id: 'a3', filename: 'devis_lune_v2.pdf', mimeType: 'application/pdf', sizeBytes: 142_018, contentHash: 'sha:ccc3' },
    ],
    engagements: [{ text: 'On revient vers toi vendredi', reminded: false }],
  },
  {
    id: 'm8',
    threadId: 't8',
    accountId: 'acc_pro',
    folder: 'inbox_pro',
    labels: [],
    from: { name: 'Linear', email: 'team@linear.app' },
    to: [{ email: 'j.lafe@triskell.studio' }],
    cc: [],
    bcc: [],
    subject: 'Weekly digest — 23 issues closed',
    bodyText: "Here is your weekly summary. 23 issues closed, 8 new bugs, 4 PRs merged.",
    receivedAt: days(3),
    read: true,
    starred: false,
    category: 'newsletters',
    priority: 'normal',
    trackersBlocked: 3,
    references: [],
    attachments: [],
  },
];

export const mockThreads: Thread[] = mockMails.map((m) => ({
  id: m.threadId,
  accountId: m.accountId,
  subject: m.subject,
  participants: [m.from, ...m.to],
  mailIds: [m.id],
  lastReceivedAt: m.receivedAt,
  hasUnread: !m.read,
  category: m.category,
}));
